[system]
# This block is used to define the behavior of core chandragen functionality.

# Defines how the scheduler should operate and, if used, what format the interval field is in. options: crontab | oneshot
# crontab: uses crontab syntax to run formatting jobs at set intervals, good for independent self-hosts
# oneshot: runs all configured jobs immediately on startup and then exits. this mode is intended for use with tools like github actions.
scheduler_mode = "crontab" 

[defaults]
# This block declares the default pipeline config, and can be overridden.
formatters = [
    "strip_inline_md_formatting",
    "convert_bullet_point_links",
    "format_tables_as_unicode",
    "convert_known_mdx_components",
    "strip_imports_exports",
    "strip_jsx_tags",
    "normalize_codeblocks"
]
output_path = "./main_gemroot/"
preformatted_text_columns = 80
interval = "0 * * * *"

[defaults.formatter_flags]
table_style = "unicode"

[file.code_of_conduct]
# config section for a single document
# entry level formatters are added on top of the default formatters list.
# formatters can be removed by blacklisting
formatters= [
    "strip_heading",
    "strip_footing",
    "convert_inline_links",
    "strip_html_comments"
]
formatter_blacklist = [
    "strip_jsx_tags",
    "strip_imports_exports",
    "normalize_codeblocks",
    "convert_known_mdx_components"
]
output_path = "./main_gemroot/code-of-conduct.gmi"
input_path = "/home/thanos/dev/atl-gemini/code-of-conduct/README.md"
heading = '''
```
  _____        __      ____  ___  _____             __         __
 / ___/__  ___/ /__   / __ \/ _/ / ___/__  ___  ___/ /_ ______/ /_
/ /__/ _ \/ _  / -_) / /_/ / _/ / /__/ _ \/ _ \/ _  / // / __/ __/
\___/\___/\_,_/\__/  \____/_/   \___/\___/_//_/\_,_/\_,_/\__/\__/
```
'''
heading_end_pattern = "<!-- END doctoc generated TOC please keep comment here to allow auto update -->\n"
heading_strip_offset = 2

#[dir.blog]
# minimal config for a directory
#recursive = true
#input_path = "./blog/*.mdx"
#output_path = "./main_gemroot/blog/"
